base_url = "http://localhost:8080"
api_server_port = "8080"
koruri_bold_font_path = "../../Koruri-Bold.ttf"
tls = false
local_dev = true

default_image_width = 1200
default_image_height = 630
default_font_size = 100.0
