root_path = "."

watch_target_dirs = ["../../"]
watch_exclude_dirs = [".git", "tmp", "data"]
watch_file_ext = [".go"]

build_target_dir = "./tmp"
build_target_name = "ogp-server"
build_command = "go"
build_options = ["build", "-v"]

start_options = ["-c", "../../conf/dev.toml"]
restart_process = true
